/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface PageInput {
  url: string
  text: string
}
export interface DuplicateResult {
  url: string
  similarPages: Array<SimilarPage>
}
export interface SimilarPage {
  url: string
  similarity: number
}
/**
 * Find near-duplicate pages using LSH
 */
export function findNearDuplicates(pages: Array<PageInput>, threshold: number, bands: number, rows: number): Array<DuplicateResult>
/**
 * Calculate MinHash signature for a single text
 */
export function generateMinhash(text: string, numHashes: number): Array<number>
/**
 * Calculate Jaccard similarity between two MinHash signatures
 */
export function jaccardSimilarity(sig1: Array<number>, sig2: Array<number>): number

